api:
    dashboard: 1

log:
    level: DEBUG
    filePath: /var/log/traefik/traefik.log

accessLog:
    filePath: /var/log/traefik/access.log

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
        network:
    file:
        directory: "/etc/traefik/dynamic"
        watch: true

entryPoints:
    http:
        address: ":80"

    https:
        address: ":443"
    mysql:
        address: ":3306"

certificatesResolvers:
    le:
        acme:
            email:
            storage: acme.json
            dnsChallenge:
                provider: cloudflare
                delayBeforeCheck: 20
                resolvers:
                    - "1.1.1.1:53"
                    - "1.0.0.1:53"
